// @ts-nocheck
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
  EthersExtension,
  ZeroDevSmartWalletConnectors,
  DynamicWagmiConnector,
} from "../lib/dynamic";
import AuthProvider from "@/components/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ref3R",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<AuthProvider>
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: process.env.DYNAMIC_PROJECT_ID || "",
            walletConnectors: [EthereumWalletConnectors],
            walletConnectorExtensions: [EthersExtension],
          }}
        >
          <DynamicWagmiConnector>{children}</DynamicWagmiConnector>
        </DynamicContextProvider>
      </body>
      </AuthProvider>
    </html>
  );
}
